// zhangjiajie-tours-v3 — Experiences module data (data-driven page generation)
// Each object feeds templates/experience-page.html via scripts/build-experiences.mjs.
// Image pool reuses existing images/*.webp files.

export const experiences = [
  {
    slug: 'avatar-bailong-elevator',
    file: 'avatar-bailong-elevator.html',
    title: 'Avatar Mountains & Bailong Elevator Experience | Visit Zhangjiajie',
    metaDesc: 'Ride the Bailong Elevator to the Yuanjiajie Avatar mountains in Zhangjiajie. The world\'s tallest outdoor lift, Hallelujah Mountain views, routes, tickets and how to beat the queues.',
    canonical: 'https://willyye.github.io/zhangjiajie-tours-v3/experiences/avatar-bailong-elevator.html',
    heroImg: 'yuanjiajie-avatar.webp',
    heroImgAlt: 'Bailong Elevator rising against the Avatar mountain pillars of Yuanjiajie',
    heroBgImg: 'yuanjiajie-mist.webp',
    breadcrumb: 'Avatar & Bailong Elevator',
    h1: 'Avatar Mountains & Bailong Elevator',
    subtitle: 'The 90-second lift to Pandora',
    heroIntro: 'Ride the world\'s tallest outdoor elevator straight up a cliff face to the Yuanjiajie plateau — the real-world landscape that inspired Avatar\'s floating Hallelujah Mountains.',
    tldr: 'The Bailong Elevator is a 326 m glass outdoor lift built into a cliff in Zhangjiajie National Forest Park, China. It lifts visitors to the Yuanjiajie plateau in about 90 seconds, opening onto the quartz-sandstone pillars that inspired Avatar.',
    introH2: 'Why this experience matters',
    introParas: [
      'Yuanjiajie is the most famous postcard of Zhangjiajie, and the Bailong Elevator is the fastest way to reach it. The lift climbs 326 m up a sheer cliff — the world\'s tallest outdoor elevator — and drops you at the rim of the Avatar viewpoint loop.',
      'For many travelers, this is the moment the landscape becomes real. The pillars that looked painted from below are suddenly beside you, wrapped in mist or glowing in sunrise. If you have only one morning in the park, this is the experience to prioritize.',
    ],
    highlightsIntro: 'The four must-sees once you step off the elevator.',
    highlights: [
      { img: 'yuanjiajie-avatar.webp', alt: 'Hallelujah Mountain viewpoint', title: 'Avatar Hallelujah Mountain', sub: 'The Avatar viewpoint', desc: 'The pillar that inspired the film\'s floating mountains. Best at sunrise before the crowds arrive.' },
      { img: 'yuanjiajie-mist.webp', alt: 'Misty pillars at Yuanjiajie', title: 'First Bridge Under Heaven', sub: 'Natural stone arch', desc: 'A narrow stone bridge connecting two pillars, just a short walk from the elevator.' },
      { img: 'peaks-panorama.webp', alt: 'Panorama of sandstone pillars', title: 'Enchanting Terrace', sub: 'Wide panorama', desc: 'A railed overlook with the classic sea-of-pillars view stretching into the distance.' },
      { img: 'intro-bg.webp', alt: 'Bailong Elevator tower', title: 'The elevator itself', sub: '326 m in 90 seconds', desc: 'The glass lift shows the cliff rushing past — dramatic, fast, and worth it for the view alone.' },
    ],
    routesIntro: 'Two ways to build this into your day.',
    routes: [
      {
        icon: 'zap', title: 'Sunrise Avatar loop', sub: '2.5–3 hours · elevator up + shuttle/walk down',
        steps: [
          { strong: 'Arrive before 07:00', text: 'enter at the East Gate and take the first shuttle to the elevator.' },
          { strong: 'Bailong Elevator up', text: 'ride to the Yuanjiajie plateau.' },
          { strong: 'Avatar viewpoint', text: 'walk to Hallelujah Mountain for sunrise photos.' },
          { strong: 'First Bridge Under Heaven', text: 'short ridge walk to the natural arch.' },
          { strong: 'Descent', text: 'return by elevator or walk down via the Golden Whip Stream path.' },
        ],
      },
      {
        icon: 'footprints', title: 'Yuanjiajie + Tianzi combo', sub: 'Full day · shuttle between plateaus',
        steps: [
          { strong: 'Bailong up early', text: 'start at the elevator for the Avatar loop.' },
          { strong: 'Rim shuttle', text: 'connect to the Tianzi Mountain ridge.' },
          { strong: 'Tianzi viewpoints', text: 'Helong Deck and Imperial Brush Peak.' },
          { strong: 'Cable car down', text: 'return to the valley by the Tianzi cable car.' },
        ],
      },
    ],
    bestTime: {
      cards: [
        { icon: 'sunrise', period: 'Sunrise', desc: 'Arrive before 07:00 for the best light and smallest queues.' },
        { icon: 'calendar-heart', period: 'Apr – May', desc: 'Spring mist and green forests.' },
        { icon: 'calendar-heart', period: 'Sep – Nov', desc: 'Crisp air and clear visibility.' },
      ],
      note: 'Avoid midday 09:00–11:00 when the elevator queues are longest. Summer afternoons can be hazy.',
    },
    tips: [
      { icon: 'clock', title: 'Beat the queues', desc: 'The first 30 minutes after opening are the quietest. Arrive at the East Gate 30 minutes before it opens.' },
      { icon: 'ticket', title: 'Ticket is separate', desc: 'Park entry (¥227) does not include the elevator. Buy the elevator ticket separately, roughly ¥65 one way.' },
      { icon: 'camera', title: 'Best photo spot', desc: 'The Avatar viewpoint is best at sunrise. The elevator top also has a small platform for a quick shot.' },
      { icon: 'users', title: 'Crowds are real', desc: 'If the elevator line is long, consider walking up via the Golden Whip Stream path — slower but scenic and quiet.' },
      { icon: 'cloud', title: 'Clouds help', desc: 'A little mist makes the pillars look like they are floating. Dry, sunny days can feel flat by comparison.' },
    ],
    gettingThere: [
      { strong: 'City → East Gate', text: 'Bus from Zhangjiajie city or railway station to the Wulingyuan East Gate, 40–60 min, ¥13.' },
      { strong: 'East Gate → elevator', text: 'Inside the park, take the shuttle to the Bailong Elevator station, ~10 min.' },
      { strong: 'Elevator up', text: 'Ride to the Yuanjiajie plateau in ~90 seconds.' },
      { strong: 'Walking option', text: 'From Golden Whip Stream, a stepped path climbs to Yuanjiajie in 1.5–2 hours.' },
    ],
    tickets: [
      { item: 'Wulingyuan combo ticket', detail: '¥227 — valid 4 days; includes shuttle bus' },
      { item: 'Bailong Elevator one-way', detail: '¥65' },
      { item: 'Bailong Elevator round-trip', detail: '¥130' },
      { item: 'Opening hours', detail: '07:00 – 17:30' },
      { item: 'Best time', detail: 'Sunrise; Apr–May, Sep–Nov' },
    ],
    facts: [
      { label: 'Elevator height', value: '326 m' },
      { label: 'Ride time', value: '88–90 seconds' },
      { label: 'Type', value: 'Outdoor cliff elevator' },
      { label: 'Best time', value: 'Sunrise' },
      { label: 'Suggested visit', value: '2–4 hours' },
      { label: 'Ticket', value: '¥227 + ¥65' },
    ],
    localTip: 'Get the first elevator of the day. By 09:00 the line can stretch for an hour, and the Avatar viewpoint loses its magic when packed with selfie sticks.',
    galleryTitle: 'Avatar Mountains & Bailong Elevator',
    gallery: [
      { img: 'yuanjiajie-avatar.webp', alt: 'Hallelujah Mountain viewpoint' },
      { img: 'yuanjiajie-mist.webp', alt: 'Misty Yuanjiajie pillars' },
      { img: 'peaks-panorama.webp', alt: 'Panorama of sandstone pillars' },
      { img: 'intro-bg.webp', alt: 'Misty Wulingyuan valley' },
      { img: 'yangjiajie-wall.webp', alt: 'Cliff wall near Yuanjiajie' },
      { img: 'tianzi-autumn.webp', alt: 'Autumn peaks' },
    ],
    faqs: [
      { q: 'How long does the Bailong Elevator take?', a: 'The ride takes roughly 88–90 seconds to climb 326 m. Most of the time is spent loading and unloading, so budget 5–10 minutes total during quiet periods and up to an hour in queues at peak times.' },
      { q: 'Is the Avatar Hallelujah Mountain the same as in the film?', a: 'The floating mountain in the film is CGI, but the real-world inspiration is the Southern Sky Pillar viewpoint at Yuanjiajie, now widely called Avatar Hallelujah Mountain. The pillars are real quartz-sandstone formations.' },
      { q: 'Do I need a separate ticket for the elevator?', a: 'Yes. The Wulingyuan combo ticket (about ¥227, valid 4 days) covers park entry and shuttle buses. The Bailong Elevator is roughly ¥65 one way or ¥130 round-trip and is purchased separately.' },
      { q: 'Can I walk up instead of taking the elevator?', a: 'Yes. A stepped path climbs from the Golden Whip Stream area to the Yuanjiajie plateau in about 1.5–2 hours. It is quieter and scenic, but steep in sections.' },
      { q: 'What is the best time to visit?', a: 'Sunrise is best for light and crowds. Spring (April–May) and autumn (September–November) offer the most reliable mist and clear skies. Midday in summer is hazy and crowded.' },
      { q: 'How long should I plan for this experience?', a: 'Allow 2.5–4 hours: 30 minutes travel to the elevator, 90 seconds up, and 2–3 hours walking the Avatar viewpoint loop. Pair it with Tianzi Mountain for a full day.' },
    ],
    related: [
      { slug: 'tianmen-mountain', img: 'peaks-panorama', alt: 'Tianmen Mountain', title: 'Tianmen Mountain', sub: 'Cable car, glass walk, Heaven\'s Gate' },
      { slug: 'glass-bridge-bungee', img: 'yangjiajie-wall', alt: 'Glass Bridge', title: 'Glass Bridge & Bungee', sub: '430 m transparent span' },
      { slug: 'helicopter-tour', img: 'tianzi-autumn', alt: 'Helicopter Tour', title: 'Helicopter Tour', sub: 'Aerial view of the pillars' },
      { slug: 'cultural-shows', img: 'gallery-painting', alt: 'Cultural Shows', title: 'Cultural Shows', sub: 'Tujia song and dance' },
    ],
    jsonld: {
      name: 'Avatar Mountains & Bailong Elevator',
      alternateName: ['Yuanjiajie', 'Hallelujah Mountain', 'Bailong Elevator', 'Avatar Mountain'],
      description: 'Ride the world\'s tallest outdoor elevator to the Yuanjiajie plateau in Zhangjiajie, home to the quartz-sandstone pillars that inspired Avatar\'s Hallelujah Mountains.',
      images: ['https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/yuanjiajie-avatar.webp', 'https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/yuanjiajie-mist.webp'],
      touristType: ['Foreign tourists', 'Avatar fans', 'Families'],
      faq: [
        { q: 'How long does the Bailong Elevator take?', a: 'The ride itself is about 90 seconds, but queues can add 5–60 minutes depending on arrival time.' },
        { q: 'Is the Avatar mountain real?', a: 'The floating mountain in the film is CGI, but the real inspiration is the Southern Sky Pillar at Yuanjiajie.' },
        { q: 'Do I need a separate elevator ticket?', a: 'Yes, the Bailong Elevator is about ¥65 one way, separate from the park combo ticket.' },
      ],
      howto: {
        name: 'Sunrise Avatar loop (2.5–3 hours)',
        steps: [
          { name: 'Arrive early', text: 'Enter the East Gate at opening and shuttle to the elevator.' },
          { name: 'Bailong Elevator up', text: 'Ride to the Yuanjiajie plateau.' },
          { name: 'Avatar viewpoint', text: 'Photograph Hallelujah Mountain at sunrise.' },
          { name: 'First Bridge Under Heaven', text: 'Walk to the natural stone arch.' },
          { name: 'Descend', text: 'Return by elevator or walk down via Golden Whip Stream.' },
        ],
      },
    },
  },

  {
    slug: 'glass-bridge-bungee',
    file: 'glass-bridge-bungee.html',
    title: 'Zhangjiajie Grand Canyon Glass Bridge & Bungee | Visit Zhangjiajie',
    metaDesc: 'Walk the Zhangjiajie Grand Canyon Glass Bridge, the world\'s longest and highest transparent glass-bottom bridge, then step off on one of the world\'s highest bungee jumps. Tickets, routes, tips.',
    canonical: 'https://willyye.github.io/zhangjiajie-tours-v3/experiences/glass-bridge-bungee.html',
    heroImg: 'yangjiajie-wall.webp',
    heroImgAlt: 'Grand Canyon Glass Bridge stretching between two cliffs',
    heroBgImg: 'peaks-panorama.webp',
    breadcrumb: 'Glass Bridge & Bungee',
    h1: 'Glass Bridge & Bungee',
    subtitle: 'Walk 430 m over the canyon — then jump off',
    heroIntro: 'The longest and highest glass-bottom bridge in the world, suspended 300 m above the Grand Canyon. Walk it, photograph it, or take the leap on one of the planet\'s highest bungee jumps.',
    tldr: 'The Zhangjiajie Grand Canyon Glass Bridge is a 430 m transparent glass-bottom bridge spanning the Grand Canyon, about 300 m above the valley floor. It also offers one of the world\'s highest bungee jumps for adrenaline seekers.',
    introH2: 'Why this experience matters',
    introParas: [
      'Part engineering marvel, part adrenaline test, the Grand Canyon Glass Bridge is impossible to ignore. The transparent deck lets you look straight down at the canyon 300 m below, and on quiet days the glass reflects the sky so completely it feels like walking on air.',
      'For most visitors, the bridge is the main event. For a few, it is the warm-up. The bungee platform at the center of the bridge is one of the highest commercial jumps in the world — a 260 m free fall into the canyon.',
    ],
    highlightsIntro: 'What to expect once you step onto the glass.',
    highlights: [
      { img: 'yangjiajie-wall.webp', alt: 'Glass bridge deck', title: 'The glass bridge', sub: '430 m transparent span', desc: 'Walk the world\'s longest and highest glass-bottom bridge, suspended between two cliffs.' },
      { img: 'peaks-panorama.webp', alt: 'View through the glass floor', title: 'Canyon view', sub: '300 m straight down', desc: 'The glass floor reveals the canyon floor far below — not for the faint of heart.' },
      { img: 'jinbianxi-rock.webp', alt: 'Bungee jump platform', title: 'Bungee jump', sub: 'One of the world\'s highest', desc: 'A 260 m leap from the center of the bridge. Reservations and health checks required.' },
      { img: 'intro-bg.webp', alt: 'Grand Canyon cliffs', title: 'Canyon walk', sub: 'Hike below the bridge', desc: 'After crossing, hike down to the canyon floor, across waterfalls, and out by boat.' },
    ],
    routesIntro: 'Two ways to experience the bridge.',
    routes: [
      {
        icon: 'zap', title: 'Bridge + canyon loop', sub: '3–4 hours · walk, hike, boat',
        steps: [
          { strong: 'Shuttle to Grand Canyon', text: 'from Wulingyuan or Zhangjiajie city.' },
          { strong: 'Cross the bridge', text: 'walk the 430 m glass span with shoe covers.' },
          { strong: 'Hike down', text: 'follow the canyon trail past waterfalls and cliffs.' },
          { strong: 'Boat exit', text: 'a short boat ride takes you to the exit gate.' },
        ],
      },
      {
        icon: 'target', title: 'Bungee package', sub: 'Half day · adrenaline focused',
        steps: [
          { strong: 'Book ahead', text: 'reserve the bungee slot online or through a guide.' },
          { strong: 'Health check', text: 'weight and basic health screening at the platform.' },
          { strong: 'The jump', text: '260 m free fall from the center of the bridge.' },
          { strong: 'Certificate + photos', text: 'usually included in the package.' },
        ],
      },
    ],
    bestTime: {
      cards: [
        { icon: 'calendar-heart', period: 'Apr – Jun', desc: 'Green canyon, mild weather.' },
        { icon: 'calendar-heart', period: 'Sep – Nov', desc: 'Clear skies, best visibility.' },
        { icon: 'sunrise', period: 'Early morning', desc: 'Smaller queues and cleaner glass.' },
      ],
      note: 'Avoid rainy days — the glass gets slippery and the canyon floor hike can be muddy. Summer afternoons are crowded.',
    },
    tips: [
      { icon: 'ticket', title: 'Book in advance', desc: 'Glass Bridge tickets sell out on weekends and holidays. Book at least one day ahead.' },
      { icon: 'shoe-prints', title: 'Shoe covers required', desc: 'You will put on cloth shoe covers before stepping onto the bridge. Wear easy-to-cover shoes.' },
      { icon: 'camera', title: 'No loose items', desc: 'Drones, tripods, and sharp objects are not allowed on the bridge. Bags may be checked.' },
      { icon: 'heart-pulse', title: 'Bungee restrictions', desc: 'Jumpers typically need to be 18–60 years old, within a weight range, and free of certain medical conditions.' },
      { icon: 'map', title: 'Combine with nearby sights', desc: 'The bridge is 30–40 minutes from Wulingyuan. Pair it with Baofeng Lake or Yellow Dragon Cave for a full day.' },
    ],
    gettingThere: [
      { strong: 'Wulingyuan → Grand Canyon', text: 'Shuttle or private car, about 30–40 minutes.' },
      { strong: 'Zhangjiajie city → Grand Canyon', text: 'Bus or private car, about 60 minutes.' },
      { strong: 'Bridge entrance', text: 'Walk from the parking area to the bridge entrance; bags are checked.' },
      { strong: 'Exit', text: 'Most visitors exit via the canyon trail and boat, returning to the same parking area.' },
    ],
    tickets: [
      { item: 'Glass Bridge + Grand Canyon', detail: '¥128–¥168 depending on season' },
      { item: 'Bungee jump', detail: '¥2,998–¥3,998 (book ahead)' },
      { item: 'Bridge only', detail: '¥88–¥138' },
      { item: 'Opening hours', detail: '08:00 – 17:30' },
      { item: 'Best time', detail: 'Early morning; Apr–Jun, Sep–Nov' },
    ],
    facts: [
      { label: 'Bridge length', value: '430 m' },
      { label: 'Height above canyon', value: '~300 m' },
      { label: 'Bungee height', value: '260 m' },
      { label: 'Type', value: 'Glass-bottom bridge' },
      { label: 'Suggested visit', value: '3–4 hours' },
      { label: 'Ticket', value: '¥128–¥168' },
    ],
    localTip: 'Go as early as possible. The glass is cleaner and the canyon shadows are deeper in the morning. The bungee platform has a separate entrance — ask staff at the bridge entrance.',
    galleryTitle: 'Glass Bridge & Grand Canyon',
    gallery: [
      { img: 'yangjiajie-wall.webp', alt: 'Glass bridge span' },
      { img: 'peaks-panorama.webp', alt: 'Canyon view from the bridge' },
      { img: 'jinbianxi-rock.webp', alt: 'Rock formations below the bridge' },
      { img: 'intro-bg.webp', alt: 'Misty canyon' },
      { img: 'tianzi-autumn.webp', alt: 'Autumn peaks' },
      { img: 'huangshizhai-winter.webp', alt: 'Winter cliffs' },
    ],
    faqs: [
      { q: 'How high is the Zhangjiajie Glass Bridge?', a: 'The bridge is about 300 m above the canyon floor and 430 m long, making it one of the highest and longest glass-bottom bridges in the world.' },
      { q: 'How much does the bungee jump cost?', a: 'The bungee jump from the center of the bridge typically costs ¥2,998–¥3,998 depending on season and package. Advance booking is strongly recommended.' },
      { q: 'Is the bridge safe?', a: 'The bridge is engineered to high safety standards and undergoes regular inspections. Glass panels are replaced as needed. Visitors must wear shoe covers and follow staff instructions.' },
      { q: 'Can I visit the bridge and the canyon in one trip?', a: 'Yes. The standard ticket includes both the bridge and a canyon hike below, ending with a short boat ride. Allow 3–4 hours.' },
      { q: 'What should I wear?', a: 'Wear comfortable walking shoes and clothes suitable for hiking. The canyon trail can be slippery after rain. Avoid high heels or open-toe shoes.' },
      { q: 'How do I get there from Wulingyuan?', a: 'The bridge is about 30–40 minutes from Wulingyuan by shuttle or private car. Many tour packages include transport.' },
    ],
    related: [
      { slug: 'avatar-bailong-elevator', img: 'yuanjiajie-avatar', alt: 'Avatar Mountains', title: 'Avatar & Bailong', sub: 'Elevator to the pillars' },
      { slug: 'tianmen-mountain', img: 'peaks-panorama', alt: 'Tianmen Mountain', title: 'Tianmen Mountain', sub: 'Cable car and glass walk' },
      { slug: 'helicopter-tour', img: 'tianzi-autumn', alt: 'Helicopter Tour', title: 'Helicopter Tour', sub: 'Aerial view of the park' },
      { slug: 'minority-local-life', img: 'huangshizhai-winter', alt: 'Local Life', title: 'Minority & Local Life', sub: 'Tujia and Miao culture' },
    ],
    jsonld: {
      name: 'Grand Canyon Glass Bridge & Bungee',
      alternateName: ['Zhangjiajie Glass Bridge', 'Grand Canyon Glass Bridge', 'Zhangjiajie Bungee'],
      description: 'Walk the world\'s longest and highest glass-bottom bridge over the Zhangjiajie Grand Canyon, or take one of the world\'s highest commercial bungee jumps from the bridge center.',
      images: ['https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/yangjiajie-wall.webp', 'https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/peaks-panorama.webp'],
      touristType: ['Adventure travelers', 'Adrenaline seekers', 'Foreign tourists'],
      faq: [
        { q: 'How high is the Glass Bridge?', a: 'About 300 m above the canyon floor, with a 430 m span.' },
        { q: 'How much is the bungee jump?', a: 'Roughly ¥2,998–¥3,998 with advance booking.' },
        { q: 'Is the bridge safe?', a: 'Yes, it is engineered to high safety standards and inspected regularly.' },
      ],
      howto: {
        name: 'Bridge + canyon loop (3–4 hours)',
        steps: [
          { name: 'Shuttle to Grand Canyon', text: 'From Wulingyuan or the city.' },
          { name: 'Cross the bridge', text: 'Walk the 430 m glass span with shoe covers.' },
          { name: 'Hike down', text: 'Follow the canyon trail past waterfalls.' },
          { name: 'Boat exit', text: 'Short boat ride to the exit gate.' },
        ],
      },
    },
  },

  {
    slug: 'tianmen-mountain',
    file: 'tianmen-mountain.html',
    title: 'Tianmen Mountain Experience: Cable Car, Glass Walk & Heaven\'s Gate | Visit Zhangjiajie',
    metaDesc: 'Tianmen Mountain cable car, 99-turn road, cliffside glass walkway, and the Heaven\'s Gate natural arch. Routes, tickets, best time and how to visit for international travelers.',
    canonical: 'https://willyye.github.io/zhangjiajie-tours-v3/experiences/tianmen-mountain.html',
    heroImg: 'peaks-panorama.webp',
    heroImgAlt: 'Tianmen Mountain with the Heaven\'s Gate natural arch',
    heroBgImg: 'tianzi-snow.webp',
    breadcrumb: 'Tianmen Mountain',
    h1: 'Tianmen Mountain',
    subtitle: 'The mountain with the giant natural arch',
    heroIntro: 'Ride the world\'s longest cable car up a 7.5 km skyway, walk a cliffside glass path, then climb 999 steps through Heaven\'s Gate — the most dramatic day trip in Zhangjiajie.',
    tldr: 'Tianmen Mountain is a separate peak south of Zhangjiajie city, famous for the 7.5 km cable car, the 99-turn road, the cliffside glass walkway, and the Heaven\'s Gate natural arch. It is a half-day to full-day experience outside the main Wulingyuan park.',
    introH2: 'Why this experience matters',
    introParas: [
      'Tianmen Mountain is not inside Wulingyuan — it stands alone just south of Zhangjiajie city. That means it is easier to reach and has a different feel: a single peak with dramatic vertical cliffs, a cave punched through the mountain, and a cable car that starts in the city and ends in the clouds.',
      'The peak is famous in China for the 99 bends of the Tongtian Avenue road, the 999 steps to Heaven\'s Gate, and the glass walkways bolted to the cliff face. For international visitors, it is the most convenient "wow" experience in Zhangjiajie.',
    ],
    highlightsIntro: 'The five highlights of a Tianmen visit.',
    highlights: [
      { img: 'peaks-panorama.webp', alt: 'Cable car above the city', title: 'World\'s longest cable car', sub: '7.5 km skyway', desc: 'A 30-minute ride from the city center up to the summit, passing over villages, roads, and forest.' },
      { img: 'tianzi-snow.webp', alt: 'Heaven\'s Gate', title: 'Heaven\'s Gate', sub: 'Natural arch cave', desc: 'A huge archway through the mountain. Reach it by climbing 999 steps or by escalator.' },
      { img: 'yangjiajie-wall.webp', alt: 'Cliffside glass walkway', title: 'Glass Walkway', sub: 'Cliff-hanging path', desc: 'A narrow glass path bolted to the cliff, with a sheer drop below your feet.' },
      { img: 'intro-bg.webp', alt: '99-turn road', title: '99 Bends Road', sub: 'Tongtian Avenue', desc: 'The dramatic mountain road with 99 switchbacks, seen from the cable car or shuttles.' },
    ],
    routesIntro: 'Two ways to see Tianmen Mountain.',
    routes: [
      {
        icon: 'zap', title: 'Classic cable car route', sub: '4–6 hours · city up, bus down',
        steps: [
          { strong: 'Cable car from city', text: 'ride the 7.5 km line up to the summit.' },
          { strong: 'West cliff walk', text: 'walk the glass pathway along the cliff edge.' },
          { strong: 'Tianmen Temple', text: 'visit the temple near the summit.' },
          { strong: 'Escalator down to arch', text: 'long cave escalators to the Heaven\'s Gate cave.' },
          { strong: '999 steps or escalator', text: 'descend to the bus station.' },
          { strong: '99-bend bus down', text: 'return to the city by shuttle bus.' },
        ],
      },
      {
        icon: 'rotate-ccw', title: 'Reverse route', sub: '4–6 hours · bus up, cable car down',
        steps: [
          { strong: 'Bus to mountain gate', text: 'ride the 99 bends up by shuttle.' },
          { strong: '999 steps up', text: 'climb to Heaven\'s Gate (or take escalator).' },
          { strong: 'Summit walk', text: 'east or west cliff pathway.' },
          { strong: 'Cable car down', text: 'return to the city by the 7.5 km cable car.' },
        ],
      },
    ],
    bestTime: {
      cards: [
        { icon: 'calendar-heart', period: 'Apr – May', desc: 'Mild weather, green forests.' },
        { icon: 'calendar-heart', period: 'Sep – Nov', desc: 'Clear skies, best views.' },
        { icon: 'sunrise', period: 'Early morning', desc: 'Smaller cable car queues.' },
      ],
      note: 'Avoid winter if the cable car is closed for maintenance. Summer weekends are packed. Check the official website before booking.',
    },
    tips: [
      { icon: 'ticket', title: 'Book tickets early', desc: 'Tianmen tickets are timed. The cable car has limited capacity and morning slots sell out first.' },
      { icon: 'route', title: 'Choose A or B route', desc: 'A = cable car up, bus down. B = bus up, cable car down. Both are good; A is more popular.' },
      { icon: 'cloud', title: 'Weather matters', desc: 'The summit is often foggy. If the forecast is clear, go. If it is foggy, visibility can be near zero.' },
      { icon: 'shoe-prints', title: 'Wear good shoes', desc: 'The 999 steps are steep. The glass walkway requires shoe covers, provided on site.' },
      { icon: 'clock', title: 'Plan a full day', desc: 'Tianmen is outside Wulingyuan. Do not try to combine it with the main park in one day.' },
    ],
    gettingThere: [
      { strong: 'From Zhangjiajie city', text: 'The cable car station is downtown, near the railway station. Walk or taxi to the station.' },
      { strong: 'From Wulingyuan', text: 'Bus or private car to the city cable car station, ~40 minutes.' },
      { strong: 'Route A', text: 'Cable car up, explore summit, bus down.' },
      { strong: 'Route B', text: 'Bus to mountain gate, climb/arch, cable car down.' },
    ],
    tickets: [
      { item: 'Tianmen Mountain ticket', detail: '¥275–¥278 (includes cable car and shuttle)' },
      { item: 'Glass walkway shoe covers', detail: '¥5 (or included)' },
      { item: 'Escalator to arch', detail: '¥32 (optional, can walk steps)' },
      { item: 'Opening hours', detail: '08:00 – 18:00' },
      { item: 'Best time', detail: 'Early morning; Apr–May, Sep–Nov' },
    ],
    facts: [
      { label: 'Cable car length', value: '7.5 km' },
      { label: 'Ride time', value: '~28 min' },
      { label: 'Elevation', value: '1,518 m' },
      { label: 'Steps to arch', value: '999' },
      { label: 'Suggested visit', value: '4–6 hours' },
      { label: 'Ticket', value: '¥275–¥278' },
    ],
    localTip: 'Book route A for the morning cable car. The west cliff walk is the best part, but it is often closed in high wind — check at the summit before queuing.',
    galleryTitle: 'Tianmen Mountain',
    gallery: [
      { img: 'peaks-panorama.webp', alt: 'Heaven\'s Gate and cable car' },
      { img: 'tianzi-snow.webp', alt: 'Snow on Tianmen' },
      { img: 'yangjiajie-wall.webp', alt: 'Cliffside walkway' },
      { img: 'intro-bg.webp', alt: 'Mountain road' },
      { img: 'tianzi-autumn.webp', alt: 'Autumn peaks' },
      { img: 'huangshizhai-winter.webp', alt: 'Winter cliffs' },
    ],
    faqs: [
      { q: 'How long is the Tianmen Mountain cable car?', a: 'The cable car is 7.5 km long and takes about 28 minutes, making it one of the longest passenger cable cars in the world.' },
      { q: 'Do I need to climb 999 steps?', a: 'No. You can take escalators through the cave to reach the Heaven\'s Gate arch. The 999 steps are optional and can be climbed up or down.' },
      { q: 'Is Tianmen Mountain included in the Wulingyuan park ticket?', a: 'No. Tianmen is a separate mountain with its own ticket, about ¥275–¥278. It is not part of the Wulingyuan combo ticket.' },
      { q: 'What is Route A and Route B?', a: 'Route A goes cable car up and bus down. Route B goes bus up and cable car down. The sights are the same, but the order reverses. Route A is more popular.' },
      { q: 'Can I visit Tianmen and Wulingyuan in one day?', a: 'It is not recommended. Tianmen alone takes 4–6 hours, and travel between the two areas adds another hour. Plan separate days.' },
      { q: 'What happens if the weather is bad?', a: 'Fog can close the glass walkways and limit views. The cable car usually still runs unless winds are extreme. Check the weather the night before.' },
    ],
    related: [
      { slug: 'avatar-bailong-elevator', img: 'yuanjiajie-avatar', alt: 'Avatar', title: 'Avatar & Bailong', sub: 'Elevator to the pillars' },
      { slug: 'glass-bridge-bungee', img: 'yangjiajie-wall', alt: 'Glass Bridge', title: 'Glass Bridge & Bungee', sub: '430 m glass span' },
      { slug: 'helicopter-tour', img: 'tianzi-autumn', alt: 'Helicopter', title: 'Helicopter Tour', sub: 'Aerial view' },
      { slug: 'cultural-shows', img: 'gallery-painting', alt: 'Shows', title: 'Cultural Shows', sub: 'Tujia performances' },
    ],
    jsonld: {
      name: 'Tianmen Mountain',
      alternateName: ['天门山', 'Heaven\'s Gate Mountain', 'Tianmen Shan'],
      description: 'Tianmen Mountain near Zhangjiajie city is famous for the world\'s longest cable car, the 99-turn Tongtian Avenue, the cliffside glass walkway, and the Heaven\'s Gate natural arch.',
      images: ['https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/peaks-panorama.webp', 'https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/tianzi-snow.webp'],
      touristType: ['Foreign tourists', 'Adventure travelers', 'Families'],
      faq: [
        { q: 'How long is the cable car?', a: '7.5 km, about 28 minutes.' },
        { q: 'Do I need to climb the 999 steps?', a: 'No, escalators are available.' },
        { q: 'Is Tianmen in Wulingyuan?', a: 'No, it is separate and requires its own ticket.' },
      ],
      howto: {
        name: 'Classic Tianmen route (4–6 hours)',
        steps: [
          { name: 'Cable car up', text: 'Ride the 7.5 km line from the city.' },
          { name: 'West cliff walk', text: 'Walk the glass pathway along the cliff.' },
          { name: 'Tianmen Temple', text: 'Visit the summit temple.' },
          { name: 'Cave escalators', text: 'Descend to Heaven\'s Gate.' },
          { name: 'Bus down', text: 'Return via the 99 bends.' },
        ],
      },
    },
  },

  {
    slug: 'helicopter-tour',
    file: 'helicopter-tour.html',
    title: 'Zhangjiajie Helicopter Tour: Aerial View of the Avatar Mountains | Visit Zhangjiajie',
    metaDesc: 'Take a helicopter tour over Zhangjiajie\'s Avatar mountains and Wulingyuan pillars. See the only complete aerial view of the UNESCO landscape, with routes, prices and booking tips.',
    canonical: 'https://willyye.github.io/zhangjiajie-tours-v3/experiences/helicopter-tour.html',
    heroImg: 'tianzi-autumn.webp',
    heroImgAlt: 'Helicopter flying over the Zhangjiajie sandstone pillars',
    heroBgImg: 'peaks-panorama.webp',
    breadcrumb: 'Helicopter Tour',
    h1: 'Helicopter Tour',
    subtitle: 'The whole park from above',
    heroIntro: 'The only way to see the full scale of Zhangjiajie\'s 3,000 pillars in one go. A short helicopter loop reveals the Avatar mountains, Wulingyuan canyon, and Tianmen peak from the sky.',
    tldr: 'Helicopter tours over Zhangjiajie offer a bird\'s-eye view of the Wulingyuan World Heritage landscape, including the Yuanjiajie Avatar mountains, Tianzi Mountain ridge, and Tianmen Mountain. Flights last 10–30 minutes and depart from helipads near the park or city.',
    introH2: 'Why this experience matters',
    introParas: [
      'Every viewpoint in Zhangjiajie shows you a piece of the landscape. A helicopter shows you the whole thing. From above, the thousands of quartz-sandstone pillars look like a stone forest rising from green valleys, and the scale becomes real for the first time.',
      'Flights are short but unforgettable. They are especially popular with photographers, families who want to skip long hikes, and visitors who have limited mobility but still want the full panorama.',
    ],
    highlightsIntro: 'What you see from the air.',
    highlights: [
      { img: 'tianzi-autumn.webp', alt: 'Aerial view of pillars', title: 'Avatar mountains', sub: 'Yuanjiajie plateau', desc: 'See the Hallelujah Mountain pillar and the Yuanjiajie ridge from directly above.' },
      { img: 'peaks-panorama.webp', alt: 'Pillar sea', title: 'Sea of pillars', sub: '3,000 sandstone towers', desc: 'The full sweep of the Wulingyuan stone forest stretching to the horizon.' },
      { img: 'yangjiajie-wall.webp', alt: 'Wall-like peaks', title: 'Yangjiajie wall', sub: 'Great wall-like ridge', desc: 'A long cliff wall that looks like a dragon from above.' },
      { img: 'intro-bg.webp', alt: 'Tianmen from above', title: 'Tianmen Mountain', sub: 'Heaven\'s Gate arch', desc: 'The natural arch and the 99-bend road from the air.' },
    ],
    routesIntro: 'Typical flight options.',
    routes: [
      {
        icon: 'plane', title: 'Short loop', sub: '10–15 minutes · Wulingyuan core',
        steps: [
          { strong: 'Helipad check-in', text: 'arrive 20 minutes early with ID.' },
          { strong: 'Safety briefing', text: 'short instructions and headphones.' },
          { strong: 'Fly over Yuanjiajie', text: 'circle the Avatar mountains.' },
          { strong: 'Return to helipad', text: 'total flight time 10–15 minutes.' },
        ],
      },
      {
        icon: 'plane', title: 'Extended loop', sub: '20–30 minutes · Wulingyuan + Tianmen',
        steps: [
          { strong: 'Wulingyuan core', text: 'Yuanjiajie and Tianzi Mountain.' },
          { strong: 'Grand Canyon', text: 'fly over the glass bridge area.' },
          { strong: 'Tianmen Mountain', text: 'see the arch and cable car from above.' },
          { strong: 'Return', text: 'longer route with more photo opportunities.' },
        ],
      },
    ],
    bestTime: {
      cards: [
        { icon: 'sunrise', period: 'Morning', desc: 'Calmest air and clearest light.' },
        { icon: 'calendar-heart', period: 'Apr – Nov', desc: 'Best visibility and weather.' },
        { icon: 'cloud', period: 'After light rain', desc: 'Mist in the valleys makes pillars pop.' },
      ],
      note: 'Helicopter flights are cancelled in high wind, heavy rain, or low cloud. Always book a backup day.',
    },
    tips: [
      { icon: 'ticket', title: 'Book in advance', desc: 'Helicopters have limited seats and weather cancels flights. Book early and keep a flexible schedule.' },
      { icon: 'camera', title: 'Camera without lens cap', desc: 'You can take photos, but loose items must be secured. Sunglasses are useful for glare.' },
      { icon: 'users', title: 'Small groups', desc: 'Most helicopters seat 3–5 passengers. Private charters are available for a premium.' },
      { icon: 'heart-pulse', title: 'Health note', desc: 'Pregnant travelers, very young children, and people with severe motion sickness should check with the operator.' },
      { icon: 'map', title: 'Combine with a park day', desc: 'The helipad is usually near Wulingyuan. Pair the morning flight with an afternoon in the park.' },
    ],
    gettingThere: [
      { strong: 'Wulingyuan helipad', text: 'Most tours depart from a helipad near the Wulingyuan scenic area.' },
      { strong: 'City transfer', text: 'Some operators offer pickup from Zhangjiajie city hotels.' },
      { strong: 'Advance booking', text: 'Reserve online, through your hotel, or via a guide.' },
      { strong: 'Weather check', text: 'Confirm the flight status the morning of, as cancellations are common.' },
    ],
    tickets: [
      { item: 'Short loop (10–15 min)', detail: '¥800–¥1,200 per person' },
      { item: 'Extended loop (20–30 min)', detail: '¥1,500–¥2,500 per person' },
      { item: 'Private charter', detail: 'From ¥8,000' },
      { item: 'Best time', detail: 'Morning; Apr–Nov' },
      { item: 'Booking', detail: 'Online or through your hotel/guide' },
    ],
    facts: [
      { label: 'Flight time', value: '10–30 min' },
      { label: 'Altitude', value: 'Low-level scenic' },
      { label: 'Capacity', value: '3–5 passengers' },
      { label: 'Best weather', value: 'Clear, calm morning' },
      { label: 'Price range', value: '¥800–¥2,500' },
      { label: 'Booking', value: 'Advance required' },
    ],
    localTip: 'Morning flights have the calmest air and the best light. If the forecast is clear, book the first slot. If mist is in the valleys, the aerial views are even more dramatic.',
    galleryTitle: 'Helicopter Tour Over Zhangjiajie',
    gallery: [
      { img: 'tianzi-autumn.webp', alt: 'Aerial pillars' },
      { img: 'peaks-panorama.webp', alt: 'Sea of pillars' },
      { img: 'yangjiajie-wall.webp', alt: 'Wall-like ridge' },
      { img: 'intro-bg.webp', alt: 'Misty valley' },
      { img: 'yuanjiajie-avatar.webp', alt: 'Avatar mountains' },
      { img: 'tianzi-snow.webp', alt: 'Snow peaks' },
    ],
    faqs: [
      { q: 'How long is a helicopter tour over Zhangjiajie?', a: 'Standard flights last 10–15 minutes. Extended loops of 20–30 minutes include Tianmen Mountain and the Grand Canyon.' },
      { q: 'How much does it cost?', a: 'Expect ¥800–¥1,200 per person for a short loop and ¥1,500–¥2,500 for an extended loop. Private charters start around ¥8,000.' },
      { q: 'Is it safe?', a: 'Licensed operators follow aviation safety rules. Flights are cancelled in high wind, heavy rain, or low cloud.' },
      { q: 'Can children take the helicopter?', a: 'Most operators allow children, but very young children may have age or height restrictions. Check with the operator.' },
      { q: 'What if the weather is bad?', a: 'Flights are cancelled in poor weather. Operators usually offer rescheduling or refunds. Book a flexible day.' },
      { q: 'Where do the helicopters depart from?', a: 'Most depart from a helipad near Wulingyuan. Some packages include transfer from Zhangjiajie city hotels.' },
    ],
    related: [
      { slug: 'avatar-bailong-elevator', img: 'yuanjiajie-avatar', alt: 'Avatar', title: 'Avatar & Bailong', sub: 'Elevator to the pillars' },
      { slug: 'tianmen-mountain', img: 'peaks-panorama', alt: 'Tianmen', title: 'Tianmen Mountain', sub: 'Cable car and arch' },
      { slug: 'glass-bridge-bungee', img: 'yangjiajie-wall', alt: 'Glass Bridge', title: 'Glass Bridge & Bungee', sub: 'Canyon adrenaline' },
      { slug: 'cultural-shows', img: 'gallery-painting', alt: 'Shows', title: 'Cultural Shows', sub: 'Tujia performances' },
    ],
    jsonld: {
      name: 'Zhangjiajie Helicopter Tour',
      alternateName: ['Helicopter flight Zhangjiajie', 'Aerial tour Zhangjiajie'],
      description: 'A scenic helicopter tour over Zhangjiajie and Wulingyuan, offering a bird\'s-eye view of the Avatar mountains, Tianzi Mountain, and Tianmen Mountain.',
      images: ['https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/tianzi-autumn.webp', 'https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/peaks-panorama.webp'],
      touristType: ['Photographers', 'Luxury travelers', 'Families'],
      faq: [
        { q: 'How long is the flight?', a: '10–15 minutes for standard loops, 20–30 minutes for extended routes.' },
        { q: 'How much does it cost?', a: '¥800–¥2,500 per person depending on route and duration.' },
        { q: 'What if weather is bad?', a: 'Flights are cancelled and usually rescheduled or refunded.' },
      ],
      howto: {
        name: 'Scenic helicopter loop (10–15 minutes)',
        steps: [
          { name: 'Check-in', text: 'Arrive 20 minutes early at the helipad.' },
          { name: 'Safety briefing', text: 'Receive headphones and instructions.' },
          { name: 'Fly over Yuanjiajie', text: 'Circle the Avatar mountains.' },
          { name: 'Return', text: 'Land after the short scenic loop.' },
        ],
      },
    },
  },

  {
    slug: 'cultural-shows',
    file: 'cultural-shows.html',
    title: 'Zhangjiajie Cultural Shows: Tianmen Fox Fairy & Tujia Performance | Visit Zhangjiajie',
    metaDesc: 'The best cultural shows in Zhangjiajie — Tianmen Fox Fairy, Charming Xiangxi, and Tujia village performances. What to expect, tickets, and how to fit them into your trip.',
    canonical: 'https://willyye.github.io/zhangjiajie-tours-v3/experiences/cultural-shows.html',
    heroImg: 'gallery-painting.webp',
    heroImgAlt: 'Tianmen Fox Fairy cultural show stage at night',
    heroBgImg: 'intro-bg.webp',
    breadcrumb: 'Cultural Shows',
    h1: 'Cultural Shows',
    subtitle: 'Tujia song, dance, and mountain legend',
    heroIntro: 'After the peaks go dark, Zhangjiajie lights up with song, dance, and storytelling. The biggest shows blend Tujia and Miao traditions with mountain mythology and modern stagecraft.',
    tldr: 'Zhangjiajie\'s evening cultural shows, including Tianmen Fox Fairy and Charming Xiangxi, bring Tujia and Miao music, dance, and legend to life. They are a relaxed way to experience local culture after a day in the park.',
    introH2: 'Why this experience matters',
    introParas: [
      'The Wuling mountains have been home to Tujia and Miao communities for centuries. Their music, dance, funeral customs, and love stories are different from the Han culture most visitors expect — and the evening shows are the easiest way to see them.',
      'Tianmen Fox Fairy is the biggest production: a love story performed in a natural amphitheatre at the foot of Tianmen Mountain, with the mountain itself as a backdrop. Charming Xiangxi is a more polished indoor show with acrobatics, fire, and elaborate costumes.',
    ],
    highlightsIntro: 'The two shows most worth your evening.',
    highlights: [
      { img: 'gallery-painting.webp', alt: 'Tianmen Fox Fairy stage', title: 'Tianmen Fox Fairy', sub: 'Outdoor mountain show', desc: 'A Tujia love legend performed at night with Tianmen Mountain as the backdrop.' },
      { img: 'intro-bg.webp', alt: 'Charming Xiangxi performers', title: 'Charming Xiangxi', sub: 'Indoor theatre show', desc: 'Song, dance, acrobatics, and fire acts celebrating the cultures of western Hunan.' },
      { img: 'yangjiajie-wall.webp', alt: 'Fire performance', title: 'Fire acts', sub: 'Traditional skills', desc: 'Fire-breathing, torch dancing, and martial arts routines are part of the spectacle.' },
      { img: 'huangshizhai-winter.webp', alt: 'Tujia dancers', title: 'Tujia folk dance', sub: 'Costume and music', desc: 'Colorful costumes, hand drums, and traditional singing from the local communities.' },
    ],
    routesIntro: 'How to fit a show into your itinerary.',
    routes: [
      {
        icon: 'moon', title: 'Tianmen Fox Fairy evening', sub: 'After a Tianmen day · 2 hours',
        steps: [
          { strong: 'Finish Tianmen by 17:00', text: 'take the bus or cable car down.' },
          { strong: 'Dinner in the city', text: 'near the Tianmen cable car station.' },
          { strong: 'Shuttle to Fox Fairy', text: 'transfer to the outdoor theatre.' },
          { strong: 'Show time', text: 'performances usually start around 20:00.' },
        ],
      },
      {
        icon: 'theater', title: 'Charming Xiangxi evening', sub: 'After Wulingyuan park · 2 hours',
        steps: [
          { strong: 'Exit the park by 17:00', text: 'return to Wulingyuan or the city.' },
          { strong: 'Dinner', text: 'local Hunan meal before the show.' },
          { strong: 'Theatre', text: 'shows are usually in Wulingyuan or the city center.' },
          { strong: 'Return to hotel', text: 'most hotels can arrange tickets and transport.' },
        ],
      },
    ],
    bestTime: {
      cards: [
        { icon: 'calendar-heart', period: 'May – Oct', desc: 'Outdoor shows run most nights.' },
        { icon: 'moon', period: 'Evening', desc: 'After a day of hiking.' },
        { icon: 'cloud-rain', period: 'Light rain OK', desc: 'Fox Fairy supplies ponchos; indoor shows are unaffected.' },
      ],
      note: 'Outdoor shows may be cancelled in heavy rain or high wind. Indoor shows are more reliable in bad weather.',
    },
    tips: [
      { icon: 'ticket', title: 'Book through your hotel', desc: 'Hotels often get better seats and include transport. Ask when you check in.' },
      { icon: 'armchair', title: 'Seat tiers matter', desc: 'VIP seats are closer to the stage but more expensive. Standard seats are fine for the overall effect.' },
      { icon: 'cloud-rain', title: 'Bring a jacket', desc: 'Evening mountain air can be cool, even in summer. Fox Fairy is outdoors.' },
      { icon: 'camera', title: 'No flash photography', desc: 'You can usually take photos, but turn off the flash. Video may be restricted.' },
      { icon: 'clock', title: 'Confirm show time', desc: 'Start times vary by season. Confirm the night before, especially in winter.' },
    ],
    gettingThere: [
      { strong: 'Tianmen Fox Fairy', text: 'Near the Tianmen Mountain base. Buses or hotel transfers from the city, ~20 minutes.' },
      { strong: 'Charming Xiangxi', text: 'Usually in Wulingyuan or Zhangjiajie city. Taxi or hotel shuttle, ~10–20 minutes.' },
      { strong: 'Hotel tickets', text: 'Most hotels and guesthouses can book tickets and transport.' },
      { strong: 'Online', text: 'Book through travel platforms or a local guide.' },
    ],
    tickets: [
      { item: 'Tianmen Fox Fairy', detail: '¥180–¥580 depending on seat tier' },
      { item: 'Charming Xiangxi', detail: '¥150–¥480 depending on seat tier' },
      { item: 'Hotel package', detail: 'Often includes transport' },
      { item: 'Show time', detail: 'Usually 20:00–21:30' },
      { item: 'Best season', detail: 'May–October' },
    ],
    facts: [
      { label: 'Top shows', value: '2 main productions' },
      { label: 'Duration', value: '1.5–2 hours' },
      { label: 'Best season', value: 'May–Oct' },
      { label: 'Language', value: 'Chinese with visual storytelling' },
      { label: 'Price range', value: '¥150–¥580' },
      { label: 'Booking', value: 'Hotel or online' },
    ],
    localTip: 'Tianmen Fox Fairy is the show to choose if you have one night. The mountain backdrop is part of the set, and the amphitheatre is cool on summer evenings. Bring a light jacket.',
    galleryTitle: 'Cultural Shows in Zhangjiajie',
    gallery: [
      { img: 'gallery-painting.webp', alt: 'Fox Fairy stage' },
      { img: 'intro-bg.webp', alt: 'Mountain amphitheatre' },
      { img: 'yangjiajie-wall.webp', alt: 'Fire performance' },
      { img: 'huangshizhai-winter.webp', alt: 'Tujia dance' },
      { img: 'tianzi-autumn.webp', alt: 'Autumn setting' },
      { img: 'peaks-panorama.webp', alt: 'Mountain backdrop' },
    ],
    faqs: [
      { q: 'What are the best cultural shows in Zhangjiajie?', a: 'The two best-known shows are Tianmen Fox Fairy, an outdoor night show at the foot of Tianmen Mountain, and Charming Xiangxi, an indoor theatre performance of song, dance, and acrobatics.' },
      { q: 'How much are tickets?', a: 'Standard seats range from ¥150 to ¥180, while VIP seats can cost ¥480 to ¥580 depending on the show and season.' },
      { q: 'Do I need to understand Chinese?', a: 'No. The performances are highly visual — dance, acrobatics, costumes, and music tell the story even if you do not speak Chinese.' },
      { q: 'Are the shows family-friendly?', a: 'Yes. Both shows are suitable for children and families. Some fire acts may be loud, but they are generally not scary.' },
      { q: 'What should I wear?', a: 'Wear layers. Outdoor shows can be cool at night. Indoor theatres are air-conditioned.' },
      { q: 'How do I get tickets?', a: 'Book through your hotel, a local guide, or online travel platforms. Hotel packages often include transport.' },
    ],
    related: [
      { slug: 'tianmen-mountain', img: 'peaks-panorama', alt: 'Tianmen', title: 'Tianmen Mountain', sub: 'Cable car and arch' },
      { slug: 'minority-local-life', img: 'huangshizhai-winter', alt: 'Local Life', title: 'Minority & Local Life', sub: 'Tujia villages and markets' },
      { slug: 'avatar-bailong-elevator', img: 'yuanjiajie-avatar', alt: 'Avatar', title: 'Avatar & Bailong', sub: 'Elevator to the pillars' },
      { slug: 'helicopter-tour', img: 'tianzi-autumn', alt: 'Helicopter', title: 'Helicopter Tour', sub: 'Aerial view' },
    ],
    jsonld: {
      name: 'Zhangjiajie Cultural Shows',
      alternateName: ['Tianmen Fox Fairy', 'Charming Xiangxi', 'Tujia show Zhangjiajie'],
      description: 'Evening cultural shows in Zhangjiajie featuring Tujia and Miao music, dance, and legend, including Tianmen Fox Fairy and Charming Xiangxi.',
      images: ['https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/gallery-painting.webp', 'https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/intro-bg.webp'],
      touristType: ['Culture travelers', 'Families', 'Evening visitors'],
      faq: [
        { q: 'What are the best shows?', a: 'Tianmen Fox Fairy and Charming Xiangxi are the two most popular.' },
        { q: 'How much are tickets?', a: 'Standard seats ¥150–¥180, VIP ¥480–¥580.' },
        { q: 'Do I need to speak Chinese?', a: 'No, the shows are visual and musical.' },
      ],
      howto: {
        name: 'Tianmen Fox Fairy evening (2 hours)',
        steps: [
          { name: 'Finish Tianmen by 17:00', text: 'Take the bus or cable car down.' },
          { name: 'Dinner in the city', text: 'Near the Tianmen cable car station.' },
          { name: 'Transfer to theatre', text: 'Hotel shuttle or taxi to the outdoor venue.' },
          { name: 'Enjoy the show', text: 'Performance usually starts at 20:00.' },
        ],
      },
    },
  },

  {
    slug: 'minority-local-life',
    file: 'minority-local-life.html',
    title: 'Minority & Local Life in Zhangjiajie: Tujia & Miao Culture | Visit Zhangjiajie',
    metaDesc: 'Experience Tujia and Miao culture in Zhangjiajie — village visits, markets, handicrafts, food, and the daily life of the mountain communities around Wulingyuan.',
    canonical: 'https://willyye.github.io/zhangjiajie-tours-v3/experiences/minority-local-life.html',
    heroImg: 'huangshizhai-winter.webp',
    heroImgAlt: 'Tujia village houses in the Wuling mountains',
    heroBgImg: 'jinbianxi-stream.webp',
    breadcrumb: 'Minority & Local Life',
    h1: 'Minority & Local Life',
    subtitle: 'The Tujia and Miao people of the Wuling mountains',
    heroIntro: 'Beyond the viewpoints, Zhangjiajie is home to Tujia and Miao communities. Visit a village, eat a village feast, and see the mountain life that shaped the culture here.',
    tldr: 'Zhangjiajie sits in the Wuling mountain region of Hunan, home to Tujia and Miao ethnic groups. Their villages, markets, food, and crafts offer a slower, more human side of the trip beyond the park viewpoints.',
    introH2: 'Why this experience matters',
    introParas: [
      'The Avatar mountains get the headlines, but the Wuling mountains have been lived in for centuries. The Tujia and Miao people farm the valleys, tend wooden villages, and keep traditions — from handwoven textiles to sour pickled vegetables — that make this region distinct from mainstream China.',
      'A village visit or market stop is the best way to break up days of hiking. It is also where you will find the most authentic food: cured pork, sour fish soup, and spicy pickled dishes served in communal meals.',
    ],
    highlightsIntro: 'Five ways to experience local life.',
    highlights: [
      { img: 'huangshizhai-winter.webp', alt: 'Tujia village', title: 'Village visit', sub: 'Wooden houses and farms', desc: 'Walk through a traditional Tujia village with wooden houses, terraced fields, and quiet lanes.' },
      { img: 'gallery-painting.webp', alt: 'Handwoven textiles', title: 'Handicrafts', sub: 'Weaving and embroidery', desc: 'Watch local women weave traditional cloth and embroider patterns passed down for generations.' },
      { img: 'food-hunan.webp', alt: 'Tujia feast', title: 'Village feast', sub: 'Communal dining', desc: 'Eat cured meats, sour vegetables, and mountain rice in a long-table feast.' },
      { img: 'jinbianxi-stream.webp', alt: 'Local market', title: 'Markets', sub: 'Morning markets', desc: 'Visit a morning market for fresh produce, spices, and street snacks.' },
    ],
    routesIntro: 'Two ways to explore local culture.',
    routes: [
      {
        icon: 'zap', title: 'Half-day village tour', sub: '3–4 hours · village + meal',
        steps: [
          { strong: 'Morning market', text: 'start at a local market near Wulingyuan.' },
          { strong: 'Village walk', text: 'visit a Tujia village with wooden houses and farms.' },
          { strong: 'Craft demo', text: 'see weaving or embroidery, with a chance to buy directly.' },
          { strong: 'Village lunch', text: 'share a communal meal with local dishes.' },
        ],
      },
      {
        icon: 'footprints', title: 'Self-guided village loop', sub: '2–3 hours · no guide needed',
        steps: [
          { strong: 'Rent a bike or taxi', text: 'head to a village within 15 minutes of Wulingyuan.' },
          { strong: 'Wander the lanes', text: 'explore wooden houses, fields, and small temples.' },
          { strong: 'Local eatery', text: 'stop at a village restaurant for rice noodles or a small meal.' },
          { strong: 'Return', text: 'taxi or bike back to your hotel.' },
        ],
      },
    ],
    bestTime: {
      cards: [
        { icon: 'calendar-heart', period: 'Apr – Jun', desc: 'Green fields, mild weather.' },
        { icon: 'calendar-heart', period: 'Sep – Nov', desc: 'Harvest season, festivals.' },
        { icon: 'sunrise', period: 'Morning', desc: 'Markets are liveliest early.' },
      ],
      note: 'Village visits are year-round. Festivals such as Tujia New Year add extra color but require planning.',
    },
    tips: [
      { icon: 'users', title: 'Hire a local guide', desc: 'A guide helps with language and connects you with families for meals and craft demos.' },
      { icon: 'hand-heart', title: 'Ask before photographing', desc: 'People are generally friendly, but ask permission before taking close-up portraits.' },
      { icon: 'utensils', title: 'Try the sour dishes', desc: 'Sour fish soup, pickled vegetables, and cured pork are Tujia specialties.' },
      { icon: 'banknote', title: 'Bring cash', desc: 'Small village shops and markets rarely accept cards.' },
      { icon: 'map', title: 'Stay near Wulingyuan', desc: 'Villages and markets are easiest to reach from a Wulingyuan base.' },
    ],
    gettingThere: [
      { strong: 'From Wulingyuan', text: 'Villages are 10–20 minutes by taxi or e-bike from the town center.' },
      { strong: 'From Zhangjiajie city', text: 'Allow 40–60 minutes by private car or taxi.' },
      { strong: 'Guided tour', text: 'Many guides offer half-day village tours with transport and a meal.' },
      { strong: 'Public transport', text: 'Limited. Taxis or hotel transport are more reliable.' },
    ],
    tickets: [
      { item: 'Village visit', detail: 'Usually free; some charge ¥10–¥30 donation' },
      { item: 'Guided half-day tour', detail: '¥200–¥400 per person including transport' },
      { item: 'Village meal', detail: '¥60–¥120 per person' },
      { item: 'Handicrafts', detail: 'Prices vary; buy directly from makers' },
      { item: 'Best time', detail: 'Morning; Apr–Jun, Sep–Nov' },
    ],
    facts: [
      { label: 'Ethnic groups', value: 'Tujia, Miao' },
      { label: 'Region', value: 'Wuling mountains, Hunan' },
      { label: 'Language', value: 'Tujia / Miao / Mandarin' },
      { label: 'Best season', value: 'Apr–Jun, Sep–Nov' },
      { label: 'Suggested visit', value: 'Half day' },
      { label: 'Cost', value: 'Free to ¥400' },
    ],
    localTip: 'Visit a morning market before 09:00. You will see the freshest produce, the best snacks, and the liveliest village energy. Buy a bag of spicy pickled vegetables to take home.',
    galleryTitle: 'Minority & Local Life in Zhangjiajie',
    gallery: [
      { img: 'huangshizhai-winter.webp', alt: 'Tujia village' },
      { img: 'gallery-painting.webp', alt: 'Handicrafts' },
      { img: 'food-hunan.webp', alt: 'Tujia feast' },
      { img: 'jinbianxi-stream.webp', alt: 'Village stream' },
      { img: 'intro-bg.webp', alt: 'Mountain village' },
      { img: 'tianzi-autumn.webp', alt: 'Autumn fields' },
    ],
    faqs: [
      { q: 'Who are the Tujia and Miao people?', a: 'The Tujia and Miao are two of China\'s officially recognized ethnic minorities. They have lived in the Wuling mountain region of Hunan for centuries and have distinct languages, music, textiles, and food traditions.' },
      { q: 'Can I visit a real village?', a: 'Yes, several villages near Wulingyuan welcome visitors. Some are more tourist-oriented than others. A local guide can help you find a quieter, more authentic village.' },
      { q: 'What food should I try?', a: 'Try sour fish soup, cured pork, pickled vegetables, and hand-pounded rice cakes. Village meals are usually served communally and are spicy.' },
      { q: 'Do I need to speak Chinese?', a: 'A guide helps, but basic gestures and a smile go a long way. Younger villagers may speak some Mandarin, but older residents often speak Tujia dialect.' },
      { q: 'Is it respectful to photograph people?', a: 'Always ask before taking close-up portraits. Most people are friendly, but some may prefer not to be photographed.' },
      { q: 'How much does a village tour cost?', a: 'A half-day guided village tour with transport and a meal typically costs ¥200–¥400 per person. Self-guided visits are much cheaper, with meals around ¥60–¥120.' },
    ],
    related: [
      { slug: 'cultural-shows', img: 'gallery-painting', alt: 'Cultural Shows', title: 'Cultural Shows', sub: 'Evening performances' },
      { slug: 'avatar-bailong-elevator', img: 'yuanjiajie-avatar', alt: 'Avatar', title: 'Avatar & Bailong', sub: 'Elevator to the pillars' },
      { slug: 'helicopter-tour', img: 'tianzi-autumn', alt: 'Helicopter', title: 'Helicopter Tour', sub: 'Aerial view' },
    ],
    jsonld: {
      name: 'Minority & Local Life in Zhangjiajie',
      alternateName: ['Tujia village visit', 'Miao culture Zhangjiajie', 'Local life Wulingyuan'],
      description: 'Experience Tujia and Miao culture in the Wuling mountains around Zhangjiajie through village visits, markets, handicrafts, and traditional food.',
      images: ['https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/huangshizhai-winter.webp', 'https://willyye.github.io/zhangjiajie-tours-v3/images/experiences/gallery-painting.webp'],
      touristType: ['Culture travelers', 'Food travelers', 'Families'],
      faq: [
        { q: 'Who are the Tujia and Miao?', a: 'They are two ethnic minority groups with long histories in the Wuling mountains of Hunan.' },
        { q: 'Can I visit a real village?', a: 'Yes, several villages near Wulingyuan welcome visitors. A guide helps find authentic ones.' },
        { q: 'What food should I try?', a: 'Sour fish soup, cured pork, pickled vegetables, and rice cakes.' },
      ],
      howto: {
        name: 'Half-day village visit (3–4 hours)',
        steps: [
          { name: 'Morning market', text: 'Start at a local market near Wulingyuan.' },
          { name: 'Village walk', text: 'Visit a Tujia village with wooden houses.' },
          { name: 'Craft demo', text: 'See weaving or embroidery.' },
          { name: 'Village meal', text: 'Share a communal local lunch.' },
        ],
      },
    },
  },
];
