// zhangjiajie-tours-v3 — Food module data
// 5 categories (mind-map: 张家界美食 / 特色餐厅 / 中餐厅 / 西餐厅 / 必吃榜).
// Dishes & restaurants researched from public Zhangjiajie dining guides (2026).
// Images are AI-generated food photos in images/ (see ImageGen run).
// Run: node scripts/build-food.mjs

export const foodCategories = [
  {
    type: 'dishes',
    slug: 'zhangjiajie-cuisine',
    title: 'Zhangjiajie Cuisine',
    tag: 'The local table',
    heroImg: 'food-tujia-feast',
    heroAlt: 'A Tujia feast of steamed pork, smoked pork and wild mushroom hotpot',
    heroTag: 'What to eat',
    h1: 'Zhangjiajie Cuisine',
    subtitle: 'Bold Hunan heat meets Tujia and Miao mountain traditions — smoked pork, fiery dry-pots, foraged mushrooms, and noodle breakfasts.',
    metaDesc: 'Zhangjiajie cuisine explained: Sanxia Guo three-pot stew, Tujia smoked pork, wild mushroom hotpot, Cili rice noodles and more.',
    intro: 'Zhangjiajie’s food is shaped by the Tujia and Miao peoples: cured and smoked meats, wild mountain vegetables, and chilli-forward cooking. Here are the dishes worth building a meal around.',
    bodyIntro: 'The signatures — order these and you’ve eaten Zhangjiajie.',
    hubDesc: 'The signature dishes of Zhangjiajie — what to order and why.',
    dishes: [
      { name: 'Sanxia Guo (Three-Pot Stew)', zh: '三下锅', img: 'food-sanxiaguo', desc: 'The city’s No.1 dish: smoked cured pork, tripe and tofu simmered in a dry chilli pot. Choose mild, medium or extra spicy.' },
      { name: 'Tujia Smoked Cured Pork', zh: '土家腊肉', img: 'food-tujia-feast', desc: 'Pork cured with salt and Sichuan pepper, then pine-smoked for two months. Stir-fried with garlic sprouts or wild bamboo shoots.' },
      { name: 'Wild Mushroom Hotpot', zh: '野山菌火锅', img: 'food-mushroom-hotpot', desc: 'A fiery winter broth simmered with forest-picked mushrooms — communal, aromatic, and deeply local.' },
      { name: 'Cili Rice Noodles', zh: '慈利米粉', img: 'food-rice-noodles', desc: 'Bouncy rice noodles with beef, pork trotter or mushroom topping. The local breakfast of choice before a day of hiking.' },
      { name: 'Tujia Steamed Pork (Zongba Rou)', zh: '土家粉蒸肉', img: 'food-tujia-feast', desc: 'Pork belly coated in fragrant rice flour and steamed with chilli and Sichuan pepper until melt-in-mouth tender.' },
      { name: 'Brown-Sugar Taro Milk Tea', zh: '茶颜悦色式', img: 'food-dessert', desc: 'Hunan’s iconic milk-tea style — a sweet, cooling counterpoint to all that chilli. A must-try for visitors.' },
    ],
  },
  {
    type: 'restaurants',
    slug: 'featured-restaurants',
    title: 'Featured Restaurants',
    tag: 'Our picks',
    heroImg: 'food-restaurant-interior',
    heroAlt: 'A cosy Zhangjiajie restaurant interior with Tujia decor',
    heroTag: 'Worth the trip',
    h1: 'Featured Restaurants',
    subtitle: 'Places we’d send friends to — characterful rooms, consistent cooking, and dishes that taste like the region.',
    metaDesc: 'Featured Zhangjiajie restaurants — Zhaisao Dangjia, Xiang Jian Tu Cai Guan, Yin xiang ni yan and more.',
    intro: 'Beyond the dishes, the room matters. These are the restaurants with a sense of place and a kitchen that delivers.',
    bodyIntro: 'Four characterful spots our guests come back for.',
    hubDesc: 'Characterful restaurants with a real sense of place.',
    restaurants: [
      { name: 'Zhaisao Dangjia', zh: '寨嫂当家', cuisine: 'Hunan · Tujia', price: '~¥49', signature: 'Sanxiaguo hot pot & crock chicken', area: 'Yongding District' },
      { name: 'Xiang Jian Tu Cai Guan', zh: '乡间土菜馆', cuisine: 'Tujia', price: 'mid-range', signature: 'Authentic Tujia flavours, acclaimed', area: 'Wulingyuan' },
      { name: 'Yin xiang ni yan', zh: '印象泥垭', cuisine: 'Hunan', price: 'mid-range', signature: 'Classic decor; delicate giant salamander', area: 'Wulingyuan' },
      { name: 'Suo Xi Shan Zhai', zh: '索溪山寨', cuisine: 'Tujia', price: 'mid-range', signature: 'Tujia diet-culture museum dining', area: 'Wulingyuan (Floral Hotel)' },
      { name: 'Tujia Old Kitchen', zh: '土家老厨房', cuisine: 'Tujia', price: '~¥88', signature: 'Tujia steamed pork with rice flour', area: 'Wulingyuan, Suoxiyu Rd' },
    ],
  },
  {
    type: 'restaurants',
    slug: 'chinese-restaurants',
    title: 'Chinese Restaurants',
    tag: 'Local flavours',
    heroImg: 'food-sanxiaguo',
    heroAlt: 'A Hunan three-pot dry hotpot on the table',
    heroTag: 'Authentic',
    h1: 'Chinese Restaurants',
    subtitle: 'Where to eat proper Hunan and Tujia cooking — from adjustable-spice kitchens to dedicated dry-pot houses.',
    metaDesc: 'Chinese restaurants in Zhangjiajie — Tang Shifu, Fuzhengyi Sanxiaguo, LAO ZAO TAI and Tujia Wild Vegetable Restaurant.',
    intro: 'For travellers who want the real thing, these kitchens lean into Hunan heat and Tujia tradition, with English-friendly menus at the top spots.',
    bodyIntro: 'Four kitchens that do the local classics right.',
    hubDesc: 'Hunan & Tujia kitchens, from adjustable-spice to dry-pot specialists.',
    restaurants: [
      { name: 'Tang Shifu Xiangxi Famous Dishes', zh: '唐师傅湘西名菜馆', cuisine: 'Hunan · Tujia', price: '~¥70', signature: 'Chopped chilli fish head, Xiangxi Sanxia Guo', area: 'Wulingyuan, Wuling Ave' },
      { name: 'Fuzhengyi Sanxiaguo', zh: '富正毅三下锅', cuisine: 'Tujia', price: '~¥60', signature: 'Dedicated Sanxiaguo dry-pot house', area: 'Wulingyuan, Wuling Rd 102' },
      { name: 'LAO ZAO TAI', zh: '老灶台', cuisine: 'Hunan', price: 'mid-range', signature: 'Wood-fired cooking, national-media pick', area: 'Tianmen Mountain' },
      { name: 'Tujia Wild Vegetable Restaurant', zh: '土家野菜馆', cuisine: 'Tujia', price: 'mid-range', signature: 'Authentic Sanxiaguo, foraged vegetables', area: 'Wulingyuan, Jinbian Rd' },
    ],
  },
  {
    type: 'restaurants',
    slug: 'western-restaurants',
    title: 'Western & Cafe Dining',
    tag: 'When you need a break',
    heroImg: 'food-western',
    heroAlt: 'A plated Western grilled chicken with roasted vegetables',
    heroTag: 'International',
    h1: 'Western & Cafe Dining',
    subtitle: 'Zhangjiajie’s local scene is overwhelmingly Hunan — so Western options cluster in hotels and cafes. Here’s where to find a familiar plate.',
    metaDesc: 'Western and cafe dining in Zhangjiajie — hotel international restaurants, buffets and coffee shops.',
    intro: 'If the chilli needs a pause, the city’s international hotels and a growing cafe scene have you covered. Expect hotel restaurants and relaxed coffee stops rather than standalone Western eateries.',
    bodyIntro: 'Reliable spots for a Western plate or a good coffee.',
    hubDesc: 'Hotel international dining and cafes when you need a break from chilli.',
    restaurants: [
      { name: 'Pullman Zhangjiajie — International', zh: '武陵源喜来登/铂尔曼西餐厅', cuisine: 'International', price: 'upscale', signature: 'Western plates & buffet', area: 'Wulingyuan' },
      { name: 'Crowne Plaza — All-Day Dining', zh: '张家界国际大酒店西餐', cuisine: 'International', price: 'mid-range', signature: 'Western & Asian buffet', area: 'Yongding District' },
      { name: 'City Cafe & Bakery', zh: '市区咖啡烘焙', cuisine: 'Cafe', price: 'casual', signature: 'Coffee, pastries, light meals', area: 'City centre' },
      { name: 'Cha Yan Yue Se', zh: '茶颜悦色', cuisine: 'Drinks', price: '~¥15–25', signature: 'Hunan’s iconic milk tea', area: 'Wulingyuan / Yongding' },
    ],
  },
  {
    type: 'restaurants',
    slug: 'must-eat-restaurants',
    title: 'Must-Eat Restaurants',
    tag: "Travellers' top list",
    heroImg: 'food-mushroom-hotpot',
    heroAlt: 'A rich wild mushroom hotpot',
    heroTag: 'The shortlist',
    h1: 'Must-Eat Restaurants',
    subtitle: 'The places Zhangjiajie visitors rate highest — pulled from traveller ranking data, not paid placements.',
    metaDesc: 'Zhangjiajie must-eat restaurants — Zhaisao Dangjia (#1), Yin xiang ni yan, Aunt Qin, LAO ZAO TAI and more.',
    intro: 'Short on time? Start here. These are the highest-rated local restaurants by real traveller rankings — a dependable shortlist.',
    bodyIntro: 'The highest-rated local restaurants, by traveller rankings.',
    hubDesc: 'The highest-rated local restaurants, by traveller rankings.',
    restaurants: [
      { name: 'Zhaisao Dangjia', zh: '寨嫂当家', cuisine: 'Hunan · Tujia', price: '~¥49', signature: '#1 must-visit; antique decor', area: 'Tianmen Mountain' },
      { name: 'Yin xiang ni yan', zh: '印象泥垭', cuisine: 'Hunan', price: 'mid-range', signature: '#3; classic decor, giant salamander', area: 'Wulingyuan' },
      { name: 'Aunt Qin Mother’s Recipe', zh: '秦姨妈妈菜', cuisine: 'Tujia', price: 'mid-range', signature: '#8; 20+ years, renowned', area: 'Tianmen Mountain' },
      { name: 'HONGCHI LAOMA', zh: '红赤老妈生态餐', cuisine: 'Hunan', price: 'mid-range', signature: '#12; firewood fish a must', area: 'Tianmen Mountain' },
      { name: 'LAO ZAO TAI', zh: '老灶台', cuisine: 'Hunan', price: 'mid-range', signature: '#12; wood-fired cooking', area: 'Tianmen Mountain' },
      { name: 'Xiang Jian Tu Cai Guan', zh: '乡间土菜馆', cuisine: 'Tujia', price: 'mid-range', signature: '#14; authentic Tujia', area: 'Wulingyuan' },
    ],
  },
];
