// zhangjiajie-tours-v3 — Hotel module data
// 7 partner hotels grouped into 4 categories (mind-map: 山野 / 精选 / 性价比 / 区域).
// Images are pre-converted webp in images/ (see /tmp/convert_hotels.py).
// Run: node scripts/build-hotels.mjs

export const hotels = {
  jimo: {
    name: 'JiMO Boutique Hotel',
    zh: '积木酒店',
    area: 'Wulingyuan Core',
    tier: 'Boutique',
    img: 'hotel-jimo-hero',
    alt: 'JiMO boutique hotel exterior at blue hour by the river',
    blurb: 'A design-led retreat tucked into the Wulingyuan valley, minutes from the east gate. Quiet rooms, a riverside terrace, and the kind of calm that makes early park mornings effortless.',
    features: ['5–10 min drive to the Wulingyuan east gate', 'Riverside terrace & garden', 'Design-led rooms with local timber'],
  },
  hetianye: {
    name: 'Hetianye Hotel',
    zh: '和田野酒店',
    area: 'Wulingyuan · Mountain side',
    tier: 'Mountain Lodge',
    img: 'hotel-hetianye-1',
    alt: 'Hetianye hotel surrounded by green peaks',
    blurb: 'A hillside lodge with balcony rooms that open straight onto the quartz-sandstone peaks. Built for travellers who want the scenery from the pillow, not just the trail.',
    features: ['Balcony rooms with peak views', 'Quiet mountain setting', 'Family & suite layouts'],
  },
  vienna: {
    name: 'Vienna International Hotel',
    zh: '维也纳国际酒店',
    area: 'Near Tianmen Cable Car',
    tier: 'Curated',
    img: 'hotel-vienna-1',
    alt: 'Vienna International Hotel daytime exterior',
    blurb: 'A polished international-standard hotel a short hop from the Tianmen Mountain cable-car station. Reliable comfort, a proper breakfast spread, and easy airport/train links.',
    features: ['Near Tianmen cable-car station', 'Full breakfast & business facilities', 'International service standard'],
  },
  boutique: {
    name: 'Homeinn Boutique (Ziwu Park)',
    zh: '如家精品酒店（紫舞公园店）',
    area: 'Zhangjiajie City · Ziwu Park',
    tier: 'Design',
    img: 'hotel-boutique-1',
    alt: 'Homeinn Boutique hotel interior at Ziwu Park',
    blurb: 'The refreshed Homeinn Boutique format — warmer materials, smarter rooms, and a location by Ziwu Park that keeps you close to the city’s eats and transport without the noise.',
    features: ['Newly refreshed boutique format', 'By Ziwu Park, city centre', 'Smart, compact rooms'],
  },
  'homeinn-plus': {
    name: 'Homeinn Plus (Ziwu Road)',
    zh: '如家酒店（子午路店）',
    area: 'Zhangjiajie City · Ziwu Road',
    tier: 'Value',
    img: 'hotel-homeinn-plus-room-3',
    alt: 'Homeinn Plus hotel at Ziwu Road',
    blurb: 'Bright, reliable and budget‑friendly, Homeinn Plus offers you a solid retreat against Zhangjiajie’s legendary peak‑forest scenery. Every travel essential is thoughtfully covered, free of superfluous add‑ons, so you can savour the magic of mist‑shrouded stone pillars without distractions.',
    features: ['Dependable value stay', 'City-centre Ziwu Road', 'Great for longer trips'],
  },
  '72qilou': {
    name: 'Homeinn (72 Qilou)',
    zh: '如家酒店（七十二奇楼店）',
    area: 'Zhangjiajie City · 72 Qilou',
    tier: 'Value',
    img: 'hotel-72qilou-1',
    alt: 'Homeinn hotel near the 72 Qilou towers',
    blurb: 'Steps from the 72 Qilou (Seven-Twelve Towers) night-life and dining district. The practical pick if you want the city’s buzz within walking distance of your room.',
    features: ['Walking distance to 72 Qilou district', 'Lively dining & night-life nearby', 'Straightforward, comfortable rooms'],
  },
  huatian: {
    name: 'Huatiancheng Suites',
    zh: '华天城',
    area: 'Zhangjiajie City Centre',
    tier: 'City',
    img: 'hotel-huatian-g1',
    alt: 'Huatiancheng city-centre suites',
    blurb: 'Spacious apartment-style suites in the heart of the city — a smart base for families and longer stays that want kitchen space, a living area, and doorstep access to transit.',
    features: ['Apartment-style suites', 'City-centre location', 'Good for families & long stays'],
  },
};

export const hotelCategories = [
  {
    slug: 'mountain-lodges',
    title: 'Mountain & Forest Lodges',
    tag: 'Best for parks',
    heroImg: 'hotel-hetianye-1',
    heroAlt: 'Hetianye mountain lodge among the peaks',
    heroTag: 'Sleep in the scenery',
    h1: 'Mountain & Forest Lodges',
    subtitle: 'Stay inside Wulingyuan and wake up to the quartz-sandstone peaks — our picks for travellers who put the park first.',
    metaDesc: 'Mountain and forest lodges near Zhangjiajie Wulingyuan — balcony rooms and boutique retreats minutes from the park gates.',
    intro: 'These are the stays that trade city convenience for scenery. Both sit close to the Wulingyuan gates, so sunrise at the pillars is a short transfer rather than a long drive.',
    bodyIntro: 'Two lodges that put you inside the landscape rather than looking at it from afar.',
    hubDesc: 'Boutique and hillside stays inside Wulingyuan — balcony rooms with peak views.',
    hotels: ['jimo', 'hetianye'],
  },
  {
    slug: 'selected-stays',
    title: 'Curated & Design Stays',
    tag: 'Our favourites',
    heroImg: 'hotel-vienna-1',
    heroAlt: 'Vienna International Hotel exterior',
    heroTag: 'Comfort, curated',
    h1: 'Curated & Design Stays',
    subtitle: 'Hotels we’d book for our own parents — international-standard comfort and refreshed boutique design, without the guesswork.',
    metaDesc: 'Curated Zhangjiajie hotels — Vienna International near Tianmen and the refreshed Homeinn Boutique by Ziwu Park.',
    intro: 'When you want the stay itself to feel good, not just the location. These two balance service standard with a bit of design.',
    bodyIntro: 'Two stays we confidently recommend for comfort and consistency.',
    hubDesc: 'International-standard and design-led hotels we routinely recommend.',
    hotels: ['vienna', 'boutique'],
  },
  {
    slug: 'value-hotels',
    title: 'Great-Value Hotels',
    tag: 'Smart spend',
    heroImg: 'hotel-72qilou-1',
    heroAlt: 'Homeinn near the 72 Qilou towers',
    heroTag: 'More trip, less room',
    h1: 'Great-Value Hotels',
    subtitle: 'Clean, dependable bases that leave more of your budget for tickets, guides, and the good meals.',
    metaDesc: 'Great-value Zhangjiajie hotels — Homeinn Plus on Ziwu Road and Homeinn by the 72 Qilou district.',
    intro: 'Value doesn’t mean compromise on the basics. Both deliver a comfortable, predictable night with the city’s eats and transit close by.',
    bodyIntro: 'Two dependable, easy-on-the-wallet bases in the city.',
    hubDesc: 'Dependable, budget-friendly stays in Zhangjiajie city.',
    hotels: ['homeinn-plus', '72qilou'],
  },
  {
    slug: 'by-area',
    title: 'City & By-Area Stays',
    tag: 'Transit hub',
    heroImg: 'hotel-huatian-1',
    heroAlt: 'Huatiancheng city-centre suites',
    heroTag: 'City base',
    h1: 'City & By-Area Stays',
    subtitle: 'Suite-style bases in the city centre — best when trains, the airport, and a kitchen matter more than a mountain view.',
    metaDesc: 'City-centre Zhangjiajie stays — spacious Huatiancheng suites close to transit and dining.',
    intro: 'For families and longer trips, a city base with space and transit access often beats a scenic but remote room. Huatiancheng gives you suites in the centre.',
    bodyIntro: 'Apartment-style suites for travellers who want space and a central address.',
    hubDesc: 'Spacious city-centre suites close to transit and dining.',
    hotels: ['huatian'],
  },
];
